### PR TITLE
Fixed extensions page not working

### PR DESCRIPTION
**Pull request by OnGle**
removed xcache as per https://github.com/turnkeylinux/tracker/issues/495

### CODE REVIEW

**Comment by JedMeister** [comment]
Did you double check this? I didn't realise it explicitly installed xcache. xcache is part of the [lamp plan](https://github.com/turnkeylinux/common/blob/master/plans/turnkey/lamp) too I'm pretty sure it will still have php-xcaxhe installed... Also needs changelog update too :smile:

**Comment by OnGle** [comment]
Yep cheers all sorted. xcache is now purged in conf.d/main to work around xcache in lamp.

**Comment by JedMeister** [comment]
Great, that looks good. Now just needs changelog! :smile:

**Comment by OnGle** [comment]
Whoops sorry :p should be all good now :)

**Pull request merged**
